// Auto-generated by Supabase — do not edit manually.
// Regenerate with: supabase gen types typescript --project-id kuneabeiwcxavvyyfjkx
// Last generated: 2026-04-27

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      agent_runs: {
        Row: {
          agent_timings: Json | null
          agents_completed: Json
          applications_sent: number
          completed_at: string | null
          errors: Json | null
          id: string
          jobs_found: number
          jobs_matched: number
          started_at: string
          status: string
          user_id: string
        }
        Insert: {
          agent_timings?: Json | null
          agents_completed?: Json
          applications_sent?: number
          completed_at?: string | null
          errors?: Json | null
          id?: string
          jobs_found?: number
          jobs_matched?: number
          started_at?: string
          status?: string
          user_id: string
        }
        Update: {
          agent_timings?: Json | null
          agents_completed?: Json
          applications_sent?: number
          completed_at?: string | null
          errors?: Json | null
          id?: string
          jobs_found?: number
          jobs_matched?: number
          started_at?: string
          status?: string
          user_id?: string
        }
      }
      analysis_history: {
        Row: {
          company: string | null
          created_at: string
          gaps: Json | null
          id: string
          improvement_plan: Json | null
          job_description: string
          job_title: string | null
          matched_skills: Json | null
          optimized_resume: string | null
          overall_score: number
          resume_text: string
          strengths: Json | null
          summary: string | null
          user_id: string
        }
        Insert: {
          company?: string | null
          created_at?: string
          gaps?: Json | null
          id?: string
          improvement_plan?: Json | null
          job_description?: string
          job_title?: string | null
          matched_skills?: Json | null
          optimized_resume?: string | null
          overall_score?: number
          resume_text?: string
          strengths?: Json | null
          summary?: string | null
          user_id: string
        }
        Update: {
          company?: string | null
          created_at?: string
          gaps?: Json | null
          id?: string
          improvement_plan?: Json | null
          job_description?: string
          job_title?: string | null
          matched_skills?: Json | null
          optimized_resume?: string | null
          overall_score?: number
          resume_text?: string
          strengths?: Json | null
          summary?: string | null
          user_id?: string
        }
      }
      email_preferences: {
        Row: {
          daily_job_alerts: boolean
          id: string
          min_match_score: number
          updated_at: string
          user_id: string
          weekly_insights: boolean
        }
        Insert: {
          daily_job_alerts?: boolean
          id?: string
          min_match_score?: number
          updated_at?: string
          user_id: string
          weekly_insights?: boolean
        }
        Update: {
          daily_job_alerts?: boolean
          id?: string
          min_match_score?: number
          updated_at?: string
          user_id?: string
          weekly_insights?: boolean
        }
      }
      interview_schedules: {
        Row: {
          candidate_email: string | null
          candidate_name: string
          candidate_profile_id: string | null
          created_at: string
          duration_minutes: number
          feedback: string | null
          id: string
          interview_type: string
          job_posting_id: string | null
          location: string | null
          meeting_link: string | null
          notes: string | null
          rating: number | null
          scheduled_at: string
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          candidate_email?: string | null
          candidate_name?: string
          candidate_profile_id?: string | null
          created_at?: string
          duration_minutes?: number
          feedback?: string | null
          id?: string
          interview_type?: string
          job_posting_id?: string | null
          location?: string | null
          meeting_link?: string | null
          notes?: string | null
          rating?: number | null
          scheduled_at: string
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          candidate_email?: string | null
          candidate_name?: string
          candidate_profile_id?: string | null
          created_at?: string
          duration_minutes?: number
          feedback?: string | null
          id?: string
          interview_type?: string
          job_posting_id?: string | null
          location?: string | null
          meeting_link?: string | null
          notes?: string | null
          rating?: number | null
          scheduled_at?: string
          status?: string
          updated_at?: string
          user_id?: string
        }
      }
      interview_sessions: {
        Row: {
          created_at: string
          id: string
          job_title: string
          messages: Json
          readiness_score: number | null
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          job_title?: string
          messages?: Json
          readiness_score?: number | null
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          job_title?: string
          messages?: Json
          readiness_score?: number | null
          user_id?: string
        }
      }
      job_applications: {
        Row: {
          applied_at: string
          company: string
          follow_up_date: string | null
          follow_up_notes: string | null
          followed_up: boolean
          id: string
          interview_stage: string | null
          job_title: string
          job_url: string | null
          notes: string | null
          outcome_detail: string | null
          response_days: number | null
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          applied_at?: string
          company?: string
          follow_up_date?: string | null
          follow_up_notes?: string | null
          followed_up?: boolean
          id?: string
          interview_stage?: string | null
          job_title?: string
          job_url?: string | null
          notes?: string | null
          outcome_detail?: string | null
          response_days?: number | null
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          applied_at?: string
          company?: string
          follow_up_date?: string | null
          follow_up_notes?: string | null
          followed_up?: boolean
          id?: string
          interview_stage?: string | null
          job_title?: string
          job_url?: string | null
          notes?: string | null
          outcome_detail?: string | null
          response_days?: number | null
          status?: string
          updated_at?: string
          user_id?: string
        }
      }
      job_postings: {
        Row: {
          candidates_matched: number | null
          company: string
          created_at: string
          department: string | null
          description: string
          id: string
          is_remote: boolean | null
          job_type: string | null
          location: string | null
          nice_to_haves: string | null
          requirements: string | null
          salary_max: number | null
          salary_min: number | null
          status: string
          title: string
          updated_at: string
          user_id: string
        }
        Insert: {
          candidates_matched?: number | null
          company?: string
          created_at?: string
          department?: string | null
          description?: string
          id?: string
          is_remote?: boolean | null
          job_type?: string | null
          location?: string | null
          nice_to_haves?: string | null
          requirements?: string | null
          salary_max?: number | null
          salary_min?: number | null
          status?: string
          title?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          candidates_matched?: number | null
          company?: string
          created_at?: string
          department?: string | null
          description?: string
          id?: string
          is_remote?: boolean | null
          job_type?: string | null
          location?: string | null
          nice_to_haves?: string | null
          requirements?: string | null
          salary_max?: number | null
          salary_min?: number | null
          status?: string
          title?: string
          updated_at?: string
          user_id?: string
        }
      }
      job_seeker_profiles: {
        Row: {
          automation_mode: string
          career_goals_long: string | null
          career_goals_short: string | null
          career_level: string | null
          certifications: Array<{ name: string; issuer: string; date: string; license_number: string }> | null
          daily_apply_cap: number
          education: Json | null
          email: string | null
          full_name: string | null
          id: string
          last_active_at: string | null
          location: string | null
          match_threshold: number
          min_match_score: number | null
          phone: string | null
          preferred_job_types: string[] | null
          remote_only: boolean | null
          salary_max: string | null
          salary_min: string | null
          salary_target: string | null
          skills: string[] | null
          summary: string | null
          target_job_titles: string[] | null
          updated_at: string
          user_id: string
          work_experience: Json | null
        }
        Insert: {
          automation_mode?: string
          career_goals_long?: string | null
          career_goals_short?: string | null
          career_level?: string | null
          certifications?: Array<{ name: string; issuer: string; date: string; license_number: string }> | null
          daily_apply_cap?: number
          education?: Json | null
          email?: string | null
          full_name?: string | null
          id?: string
          last_active_at?: string | null
          location?: string | null
          match_threshold?: number
          min_match_score?: number | null
          phone?: string | null
          preferred_job_types?: string[] | null
          remote_only?: boolean | null
          salary_max?: string | null
          salary_min?: string | null
          salary_target?: string | null
          skills?: string[] | null
          summary?: string | null
          target_job_titles?: string[] | null
          updated_at?: string
          user_id: string
          work_experience?: Json | null
        }
        Update: {
          automation_mode?: string
          career_goals_long?: string | null
          career_goals_short?: string | null
          career_level?: string | null
          certifications?: Array<{ name: string; issuer: string; date: string; license_number: string }> | null
          daily_apply_cap?: number
          education?: Json | null
          email?: string | null
          full_name?: string | null
          id?: string
          last_active_at?: string | null
          location?: string | null
          match_threshold?: number
          min_match_score?: number | null
          phone?: string | null
          preferred_job_types?: string[] | null
          remote_only?: boolean | null
          salary_max?: string | null
          salary_min?: string | null
          salary_target?: string | null
          skills?: string[] | null
          summary?: string | null
          target_job_titles?: string[] | null
          updated_at?: string
          user_id?: string
          work_experience?: Json | null
        }
      }
      notifications: {
        Row: {
          action_url: string | null
          created_at: string
          id: string
          is_read: boolean
          message: string
          title: string
          type: string
          user_id: string
        }
        Insert: {
          action_url?: string | null
          created_at?: string
          id?: string
          is_read?: boolean
          message?: string
          title?: string
          type?: string
          user_id: string
        }
        Update: {
          action_url?: string | null
          created_at?: string
          id?: string
          is_read?: boolean
          message?: string
          title?: string
          type?: string
          user_id?: string
        }
      }
      offers: {
        Row: {
          base_salary: number | null
          bonus: number | null
          company: string
          created_at: string
          deadline: string | null
          equity: number | null
          id: string
          job_title: string
          market_rate: number | null
          negotiation_strategy: Json | null
          notes: string | null
          status: string
          total_comp: number | null
          updated_at: string
          user_id: string
        }
        Insert: {
          base_salary?: number | null
          bonus?: number | null
          company?: string
          created_at?: string
          deadline?: string | null
          equity?: number | null
          id?: string
          job_title?: string
          market_rate?: number | null
          negotiation_strategy?: Json | null
          notes?: string | null
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          base_salary?: number | null
          bonus?: number | null
          company?: string
          created_at?: string
          deadline?: string | null
          equity?: number | null
          id?: string
          job_title?: string
          market_rate?: number | null
          negotiation_strategy?: Json | null
          notes?: string | null
          status?: string
          updated_at?: string
          user_id?: string
        }
      }
      outreach_contacts: {
        Row: {
          company: string
          contact_name: string
          created_at: string
          id: string
          message_sent: string | null
          notes: string | null
          platform: string | null
          response_status: string
          role: string | null
          sent_at: string | null
          user_id: string
        }
        Insert: {
          company?: string
          contact_name?: string
          created_at?: string
          id?: string
          message_sent?: string | null
          notes?: string | null
          platform?: string | null
          response_status?: string
          role?: string | null
          sent_at?: string | null
          user_id: string
        }
        Update: {
          company?: string
          contact_name?: string
          created_at?: string
          id?: string
          message_sent?: string | null
          notes?: string | null
          platform?: string | null
          response_status?: string
          role?: string | null
          sent_at?: string | null
          user_id?: string
        }
      }
      referrals: {
        Row: {
          converted_at: string | null
          created_at: string
          id: string
          referral_code: string
          referred_email: string
          referred_user_id: string | null
          referrer_id: string
          status: string
        }
        Insert: {
          converted_at?: string | null
          created_at?: string
          id?: string
          referral_code: string
          referred_email: string
          referred_user_id?: string | null
          referrer_id: string
          status?: string
        }
        Update: {
          converted_at?: string | null
          created_at?: string
          id?: string
          referral_code?: string
          referred_email?: string
          referred_user_id?: string | null
          referrer_id?: string
          status?: string
        }
      }
      resume_versions: {
        Row: {
          created_at: string
          id: string
          job_type: string | null
          resume_text: string
          updated_at: string
          user_id: string
          version_name: string
        }
        Insert: {
          created_at?: string
          id?: string
          job_type?: string | null
          resume_text?: string
          updated_at?: string
          user_id: string
          version_name?: string
        }
        Update: {
          created_at?: string
          id?: string
          job_type?: string | null
          resume_text?: string
          updated_at?: string
          user_id?: string
          version_name?: string
        }
      }
      scraped_jobs: {
        Row: {
          company: string
          compensation_breakdown: Json | null
          description: string | null
          first_seen_at: string
          flag_reasons: string[] | null
          id: string
          is_active: boolean
          is_flagged: boolean | null
          is_remote: boolean | null
          job_type: string | null
          location: string | null
          market_rate: number | null
          posted_at: string | null
          quality_score: number | null
          salary_currency: string | null
          salary_max: number | null
          salary_min: number | null
          salary_range_estimated: Json | null
          source: string | null
          source_id: string | null
          title: string
          updated_at: string
          url: string | null
        }
        Insert: {
          company?: string
          compensation_breakdown?: Json | null
          description?: string | null
          first_seen_at?: string
          flag_reasons?: string[] | null
          id?: string
          is_active?: boolean
          is_flagged?: boolean | null
          is_remote?: boolean | null
          job_type?: string | null
          location?: string | null
          market_rate?: number | null
          posted_at?: string | null
          quality_score?: number | null
          salary_currency?: string | null
          salary_max?: number | null
          salary_min?: number | null
          salary_range_estimated?: Json | null
          source?: string | null
          source_id?: string | null
          title?: string
          updated_at?: string
          url?: string | null
        }
        Update: {
          company?: string
          compensation_breakdown?: Json | null
          description?: string | null
          first_seen_at?: string
          flag_reasons?: string[] | null
          id?: string
          is_active?: boolean
          is_flagged?: boolean | null
          is_remote?: boolean | null
          job_type?: string | null
          location?: string | null
          market_rate?: number | null
          posted_at?: string | null
          quality_score?: number | null
          salary_currency?: string | null
          salary_max?: number | null
          salary_min?: number | null
          salary_range_estimated?: Json | null
          source?: string | null
          source_id?: string | null
          title?: string
          updated_at?: string
          url?: string | null
        }
      }
      user_portfolio_items: {
        Row: {
          created_at: string
          description: string | null
          display_order: number
          id: string
          image_url: string | null
          item_type: string
          tags: string[] | null
          title: string
          url: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          display_order?: number
          id?: string
          image_url?: string | null
          item_type?: string
          tags?: string[] | null
          title?: string
          url?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          description?: string | null
          display_order?: number
          id?: string
          image_url?: string | null
          item_type?: string
          tags?: string[] | null
          title?: string
          url?: string | null
          user_id?: string
        }
      }
      learning_events: {
        Row: {
          application_id: string | null
          created_at: string
          features: Json
          id: string
          insights: Json | null
          job_id: string | null
          outcome: string
          user_id: string
        }
        Insert: {
          application_id?: string | null
          created_at?: string
          features?: Json
          id?: string
          insights?: Json | null
          job_id?: string | null
          outcome?: string
          user_id: string
        }
        Update: {
          application_id?: string | null
          created_at?: string
          features?: Json
          id?: string
          insights?: Json | null
          job_id?: string | null
          outcome?: string
          user_id?: string
        }
      }
    }
      user_profiles: {
        Row: {
          id:               string
          user_id:          string
          full_name:        string | null
          current_position:     string | null
          target_roles:     string[]
          skills:           string[]
          experience_level: string | null
          location:         string | null
          open_to_remote:   boolean
          created_at:       string
          updated_at:       string
        }
        Insert: {
          id?:               string
          user_id:           string
          full_name?:        string | null
          current_position?:     string | null
          target_roles?:     string[]
          skills?:           string[]
          experience_level?: string | null
          location?:         string | null
          open_to_remote?:   boolean
          created_at?:       string
          updated_at?:       string
        }
        Update: {
          id?:               string
          user_id?:          string
          full_name?:        string | null
          current_position?:     string | null
          target_roles?:     string[]
          skills?:           string[]
          experience_level?: string | null
          location?:         string | null
          open_to_remote?:   boolean
          created_at?:       string
          updated_at?:       string
        }
      }
      career_profiles: {
        Row: {
          user_id:         string
          full_name:       string | null
          phone:           string | null
          contact_email:   string | null
          linkedin_url:    string | null
          location:        string | null
          headline:        string | null
          summary:         string | null
          skills:          string[]
          work_experience: Json
          education:       Json
          certifications:  Array<{ name: string; issuer: string; date: string; license_number: string }>
          portfolio_items: Json
          raw_text:        string | null
          raw_text_format: string | null
          created_at:      string
          updated_at:      string
        }
        Insert: {
          user_id:          string
          full_name?:       string | null
          phone?:           string | null
          contact_email?:   string | null
          linkedin_url?:    string | null
          location?:        string | null
          headline?:        string | null
          summary?:         string | null
          skills?:          string[]
          work_experience?: Json
          education?:       Json
          certifications?:  Array<{ name: string; issuer: string; date: string; license_number: string }>
          portfolio_items?: Json
          raw_text?:        string | null
          raw_text_format?: string | null
          created_at?:      string
          updated_at?:      string
        }
        Update: {
          user_id?:         string
          full_name?:       string | null
          phone?:           string | null
          contact_email?:   string | null
          linkedin_url?:    string | null
          location?:        string | null
          headline?:        string | null
          summary?:         string | null
          skills?:          string[]
          work_experience?: Json
          education?:       Json
          certifications?:  Array<{ name: string; issuer: string; date: string; license_number: string }>
          portfolio_items?: Json
          raw_text?:        string | null
          raw_text_format?: string | null
          created_at?:      string
          updated_at?:      string
        }
      }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
  }
}

// Convenience helpers
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']
export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
